language: python

python:
  - 3.8

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  # Useful for debugging any issues with conda
  - conda info -a

  # Create environment and install dependences dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install -q --yes compilers matplotlib pytest pytest-cov coveralls pip openmdao jsonschema ruamel_yaml pyyaml make xlrd cython pandas numpydoc six setuptools git numpy scipy geopy testflo cmake dill smt seaborn
  - pip install simpy marmot-agents nlopt fatpack
  
  # Install WEIS
  #- travis_wait 60 pip install --verbose -e .;
  - travis_wait 60 python setup.py develop
  
script:
  - testflo weis
