channels:
  - conda-forge
  - defaults

dependencies:
  - dash
  - dill
  - jsonmerge
  - mat4py
  - nlopt
  - openfast
  - openraft
  - osqp  
  - pcrunch
  - pip
  - pyhams>=1.3
  - rosco
  - scipy<1.14
  - smt
  - wisdem
  - pip:
    - dash-bootstrap-components
    - dash-mantine-components
    - dearpygui
    - marmot-agents
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py # [not win]
