channels:
  - conda-forge
  - defaults

dependencies:
  - alabaster
  - babel
  - cmake
  - control
  - coveralls
  - cython
  - dill
  - docutils
  - et-xmlfile
  - fatpack
  - future
  - git
  - gdown
  - imagesize
  - jinja2
  - jsonmerge
  - jsonschema
  - make
  - markupsafe
  - matplotlib-base
  - meson
  - moorpy
  - ninja
  - nlopt
  - numpy>=1.26
  - numpydoc
  - openfast
  - openmdao<3.28
  - openraft
  - openpyxl
  #- osqp # Works with the pip version, but not the conda version
  - pandas
  - patsy
  - pcrunch
  - pip
  - pygments
  - pyhams
  - pyoptsparse
  - pytest
  - pytest-cov
  - python-benedict
  - pyyaml
  - pyzmq
  - qdldl-python
  - ruamel.yaml
  - scipy
  - seaborn
  - setuptools
  - simpy
  - slycot
  - sortedcontainers
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - statsmodels
  - swig
  - treon
  - pyzmq
  - wisdem
#  - versioneer
  - pip:
    - dearpygui
    - marmot-agents
    - osqp
    - smt
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py # [not win]
