channels:
  - conda-forge
  - defaults

dependencies:
  - git
  - mat4py
  - moorpy
  - nlopt
  - openfast=3.5.1
  - openraft
  - openpyxl
  #- osqp # Works with the pip version, but not the conda version
  - pandas
  - patsy
  - pcrunch
  - pip
  - pyhams
  - pyoptsparse
  - qdldl-python
  - rosco
  - setuptools
  - wisdem
#  - versioneer
  - pip:
    - dearpygui
    - marmot-agents
    - osqp
    - smt
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py # [not win]
