general:
    folder_output: /Users/dzalkind/Tools/WEIS-4/outputs/focct/3_FOCCT_WEIS_RAFT
    fname_output: refturb_output


driver:
  optimization:
    flag: False           # Flag to enable optimization
    solver: LN_COBYLA         # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
    tol: 1.e-2            # Optimality tolerance
    max_iter: 2          # Maximum number of iterations (SLSQP)

recorder:
    flag: True              # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
    includes: ['*raft*','*floating*','*platform*']