general:
    folder_output: outputs/DV1_test
    fname_output: iea15mw
    
design_variables:
  tower:
    rho:
      flag: False
      lower_bound: 5000.
      upper_bound: 10000.
    E:
      flag: False
      lower_bound: 100.e9
      upper_bound: 300.e9
    section_height:
      flag: False
      lower_bound: 2.5
      upper_bound: 7.5
    outer_diameter:
      flag: False
      lower_bound: 3.87
      upper_bound: 8.0
    layer_thickness:
      flag: False
      lower_bound: 4e-3
      upper_bound: 2e-1
      
  floating:
        members:
            flag: True
            groups:
                - names: [main_column]
                  ballast:
                      lower_bound: 350
                      upper_bound: 650
                  # diameter:
                  #     lower_bound: 0.1
                  #     upper_bound: 100.0
                # - names: [column1]
                #   ballast:
                #       lower_bound: 350
                #       upper_bound: 650
                # - names: [column2]
                #   ballast:
                #       lower_bound: 350
                #       upper_bound: 650
                # - names: [column3]
                #   ballast:
                #       lower_bound: 350
                #       upper_bound: 650
            

constraints:
  tower:
    height_constraint:
      flag: False
      lower_bound: 0.01
      upper_bound: 0.01
    stress:
      flag: False
    global_buckling:
      flag: False
    shell_buckling:
      flag: False
  floating:
        buoyancy:
            flag: False
        fixed_ballast_capacity:
            flag: False
        variable_ballast_capacity:
            flag: False
        metacentric_height:
            flag: False
  control:
    rotor_overspeed:
      flag: False
      # min: 0.0
      max: 0.2
    Max_PtfmPitch:
      flag: False
      max: 6

merit_figure: LCOE

driver:
  optimization:
    flag: True      # Flag to enable optimization
    solver: LN_COBYLA
    max_iter: 100
    #form: forward
  design_of_experiments:
    flag: False            # Flag to enable design of experiments
    run_parallel: True    # Flag to run using parallel processing
    generator: Uniform #FullFact   # Type of input generator. (Uniform)
    num_samples: 1      # number of samples for (Uniform only)

recorder:
    flag: True             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
    just_dvs: True          
