general:
    folder_output: outputs/doe_test2
    fname_output: iea15mw
    
design_variables:
  tower:
    rho:
      flag: True
      lower_bound: 5000.
      upper_bound: 10000.
    E:
      flag: False
      lower_bound: 100.e9
      upper_bound: 300.e9
    section_height:
      flag: False
      lower_bound: 2.5
      upper_bound: 7.5
    outer_diameter:
      flag: False
      lower_bound: 3.87
      upper_bound: 8.0
    layer_thickness:
      flag: False
      lower_bound: 4e-3
      upper_bound: 2e-1

constraints:
  tower:
    height_constraint:
      flag: False
      lower_bound: 1.e-2
      upper_bound: 1.e-2
    
  control:
    rotor_overspeed:
      flag: False
      # min: 0.0
      max: 0.2
    Max_PtfmPitch:
      flag: False
      max: 3

merit_figure: LCOE

driver:
  optimization:
    flag: True         # Flag to enable optimization
    solver: trust-constr
    max_iter: 2000
    #form: forward
  design_of_experiments:
    flag: False            # Flag to enable design of experiments
    run_parallel: False    # Flag to run using parallel processing
    generator: FullFact    # Type of input generator. (Uniform)
    num_samples: 3       # number of samples for (Uniform only)

recorder:
    flag: True             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
    just_dvs: True          
