name: CI_WEIS

# We run CI on push commits on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"] #, "macOS-latest"]
        python-version: ["3.8"]
        
    steps:
      - uses: actions/checkout@v2
          
      - name: Show custom environment1
        shell: bash
        run: cat $GITHUB_ENV
          
      - name: Print environment1
        shell: bash
        run: printenv
        
      #- uses: conda-incubator/setup-miniconda@v2
      #  # https://github.com/marketplace/actions/setup-miniconda
      #  with:
      #    #miniconda-version: "latest"
      #    channels: conda-forge
      #    auto-update-conda: true
      #    python-version: 3.8
      #    environment-file: environment.yml
        
      - uses: s-weigand/setup-conda@v1
        # https://github.com/marketplace/actions/setup-conda
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: conda-forge
          activate-conda: true
      - run: conda env update -n base --file environment.yml

      - name: Show custom environment2
        shell: bash
        run: cat $GITHUB_ENV
          
      - name: Print environment2
        shell: bash
        run: printenv
          
      #- name: which2
      #  shell: bash
      #  run: type -a tmate
        
      # Debugging session
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
